import jsPDF from "jspdf";

interface ReportData {
  divisi_name: string;
  company_name: string;
  findings: string | null;
  recommendations: string | null;
  generated_at: string;
}

export function generateAuditPDF(report: ReportData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 25;

  // Header
  doc.setFillColor(37, 99, 175);
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("AUDIT REPORT", margin, y);
  y += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Internal Chatbot Audit System", margin, y);
  y = 55;

  // Info section
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Division:", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(report.divisi_name, margin + 35, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("Company:", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(report.company_name, margin + 35, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("Date:", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(new Date(report.generated_at).toLocaleString(), margin + 35, y);
  y += 15;

  // Separator
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  // Findings
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 175);
  doc.text("Temuan (Findings)", margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 50);
  const findingsText = report.findings || "No findings recorded.";
  const findingsLines = doc.splitTextToSize(findingsText, contentWidth);
  doc.text(findingsLines, margin, y);
  y += findingsLines.length * 5 + 12;

  // Recommendations
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 175);
  doc.text("Rekomendasi (Recommendations)", margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 50);
  const recoText = report.recommendations || "No recommendations provided.";
  const recoLines = doc.splitTextToSize(recoText, contentWidth);
  doc.text(recoLines, margin, y);

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Internal Chatbot Audit System", margin, pageHeight - 10);
  doc.text(`Page 1`, pageWidth - margin - 10, pageHeight - 10);

  doc.save(`audit-report-${report.divisi_name.replace(/\s+/g, "-").toLowerCase()}.pdf`);
}
